version: '3.8'

services:
  django:
    image: poc-auth-web-app
    container_name: poc_web
    build: 
      context: .
      target: build
    volumes:
      - ./app:/home/user_app/web 
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres_db
    networks:
      - web
      - database
    tty: true
    command: "python manage.py runserver 0.0.0.0:8000"
    stdin_open: true

  postgres_db:
    container_name: poc_internal_db
    image: postgres:13.4-alpine    
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env.prod.db
    networks:
      - web
      - database

  postgres_external_db:
    container_name: poc_external_db
    image: postgres:13.4-alpine    
    volumes:
      - postgres_external_db:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    env_file:
      - ./.env.prod.db
    networks:
      - web
      - database      

volumes:
  postgres_data:
  postgres_external_db:

networks:
  web:
  database: